language: node_js
node_js:
  - 12

install:
  - npm install -g firebase-tools

script:
  - cd client
  - yarn
  - ENV_FILE=.env.production yarn run build
  - cd $TRAVIS_BUILD_DIR

deploy:
  provider: script
  script: firebase deploy --token $FIREBASE_TOKEN
  skip_cleanup: true
  on:
    repo: 9bt/gbf-hihi-counter
    branch: master
